<?php
$ponies = array(
    "break0"    => "Mane six",
    "twilight"  => array("filename" => './twilight.png',    "first" => "Twilight",          "second" => " Sparkle", "source" => "http://fav.me/d5mddbk"),
    "rarity"    => array("filename" => './rarity.png',      "first" => "Rari",              "second" => "ty",       "source" => "http://fav.me/d53i50w"),
    "applejack" => array("filename" => './applejack.png',   "first" => "Apple",             "second" => "jack",     "source" => "http://fav.me/d4xj7oa"),
    "rainbow"   => array("filename" => './rainbow.png',     "first" => "Rainbow",           "second" => " Dash",    "source" => "http://fav.me/d5ztqnj"),
    "flutter"   => array("filename" => './fluttershy.png',  "first" => "Flutter",           "second" => "shy",      "source" => "http://fav.me/d5zhj5b"),
    "pinkie"    => array("filename" => './pinkie.png',      "first" => "Pinkie",            "second" => " Pie",     "source" => "http://fav.me/d5ugots"),
    "break1"    => "Dragons",
    "spike"     => array("filename" => './spike.png',       "first" => "Spi",               "second" => "ke",       "source" => "http://fav.me/d5mkrl5"),
    "break2"    => "The CMC",
    "sweetie"   => array("filename" => './sweetie.png',     "first" => "Sweetie",           "second" => " Belle",   "source" => "http://fav.me/d46ybmv"),
    "scoot"     => array("filename" => './scootaloo.png',   "first" => "Scoota",            "second" => "loo",      "source" => "http://fav.me/d5stgpu"),
    "abloom"    => array("filename" => './applebloom.png',  "first" => "Apple",             "second" => " Bloom",   "source" => "http://fav.me/d4m502j"),
    "babs"      => array("filename" => './babs.png',        "first" => "Babs",              "second" => " Seed",    "source" => "http://fav.me/d5qwk2n"),
    "break3"    => "Princesses",
    "celestia"  => array("filename" => './celestia.png',    "first" => "Princess Cele",     "second" => "stia",     "source" => "http://fav.me/d61hwe4"),
    "luna"      => array("filename" => './luna.png',        "first" => "Princess Lu",       "second" => "na",       "source" => "http://fav.me/d5f8k46"),
    "cadence"   => array("filename" => './cadence.png',     "first" => "Princess Ca",       "second" => "dance",    "source" => "http://fav.me/d5mi1md"),
    "twilight_p"=> array("filename" => './twilight_p.png',  "first" => "Princess Twi",      "second" => "light",    "source" => "http://fav.me/d5vcvux"),
    "break4"    => "Stallions",
    "bigmac"    => array("filename" => './bigmac.png',      "first" => "Big Mac",           "second" => "intosh",   "source" => "http://fav.me/d4vnf8c"),
    "shining"   => array("filename" => './shining.png',     "first" => "Shining",           "second" => " Armor",   "source" => "http://fav.me/d5m9yay"),
    "blueblood" => array("filename" => './blueblood.png',   "first" => "Blue",              "second" => "blood",    "source" => "http://fav.me/d3rh8rk"),
    "braeburn"  => array("filename" => './braeburn.png',    "first" => "Brae",              "second" => "burn",     "source" => "http://fav.me/d5rznvn"),
    "fancy"     => array("filename" => './fancy.png',       "first" => "Fancy",             "second" => " Pants",   "source" => "http://fav.me/d4v4kv8"),
    "break5"    => "Zebras",
    "zecora"    => array("filename" => './zecora.png',      "first" => "Zeco",              "second" => "ra",       "source" => "http://fav.me/d5bfzw0"),
    "break6"    => "Antagonists",
    "nmm"       => array("filename" => './nmm.png',         "first" => "Nightmare",         "second" => " Moon",    "source" => "http://fav.me/d566bx9"),
    "chrys"     => array("filename" => './chrysalis.png',   "first" => "Queen Chry",        "second" => "salis",    "source" => "http://fav.me/d5d44an"),
    "sombra"    => array("filename" => './sombra.png',      "first" => "King Somb",         "second" => "ra",       "source" => "http://fav.me/d5jha7c"),
    "break66"   => "Reformed antagonists",
    "sunset"    => array("filename" => './sunset.png',      "first" => "Sunset",            "second" => " Shimmer",  "source" => "http://fav.me/d73yik4"),
    "trixie"    => array("filename" => './trixie.png',      "first" => "Tri",               "second" => "xie",      "source" => "http://fav.me/d4bwy8z"),
    "gilda"     => array("filename" => './gilda.png',       "first" => "Gil",               "second" => "da",       "source" => "http://fav.me/d46xxlx"),
    "discord"   => array("filename" => './discord.png',     "first" => "Dis",               "second" => "cord",     "source" => "http://fav.me/d5ke8hx"),
    "break7"    => "Minor characters",
    "diamond"   => array("filename" => './diamond.png',     "first" => "Diamond",           "second" => " Tiara",   "source" => "http://fav.me/d4n0c41"),
    "silver"    => array("filename" => './silver.png',      "first" => "Silver",            "second" => " Spoon",   "source" => "http://fav.me/d54k0up"),
    "cheerilee" => array("filename" => './cheerilee.png',   "first" => "Cheeri",            "second" => "lee",      "source" => "http://fav.me/d5vpgin"),
    "granny"    => array("filename" => './granny.png',      "first" => "Granny",            "second" => " Smith",   "source" => "http://fav.me/d4gd7rm"),
    "spitfire"  => array("filename" => './spitfire.png',    "first" => "Spit",              "second" => "fire",     "source" => "http://fav.me/d567ehb"),
    "fleur"     => array("filename" => './fleur.png',       "first" => "Fleur",             "second" => " Dis Lee", "source" => "http://fav.me/d4i52vp"),
    "break8"    => "Background ponies",
    "bonbon"    => array("filename" => './bonbon.png',      "first" => "Bon",               "second" => "bon",      "source" => "http://fav.me/d5ioklg"),
    "lyra"      => array("filename" => './lyra.png',        "first" => "Ly",                "second" => "ra",       "source" => "http://fav.me/d3hyr2w"),
    "derpy"     => array("filename" => './derpy.png',       "first" => "Der",               "second" => "py",       "source" => "http://fav.me/d6evhhb"),
    "doctor"    => array("filename" => './doctor.png',      "first" => "Doctor",            "second" => " Whooves", "source" => "http://fav.me/d68lnfu"),
    "golden"    => array("filename" => './golden.png',      "first" => "Golden",            "second" => " Harvest", "source" => "http://fav.me/d3hd94p"),
    "octavia"   => array("filename" => './octavia.png',     "first" => "Octa",              "second" => "via",      "source" => "http://fav.me/d49q8xr"),
    "vinyl"     => array("filename" => './vinyl.png',       "first" => "Vinyl",             "second" => " Scratch", "source" => "http://fav.me/d4xvn1e"),
    "vinyl2"    => array("filename" => './vinyl2.png',      "first" => "Vinyl",             "second" => " Scratch", "source" => "http://fav.me/d3hglym",    "hidden" => true),
    "break9"    => "Pets",
    "angel"     => array("filename" => './angel.png',       "first" => "An",                "second" => "gel",      "source" => "http://fav.me/d4mffi4"),
    "opal"      => array("filename" => './opal.png',        "first" => "Opal",              "second" => "escence",  "source" => "http://fav.me/d3gsxji"),
    "gummy"     => array("filename" => './gummy.png',       "first" => "Gum",               "second" => "my",       "source" => "http://fav.me/d5j6tze"),
    "owl"       => array("filename" => './owl.png',         "first" => "Owlow",             "second" => "iscious",  "source" => "http://fav.me/d5kibis"),
    "tank"      => array("filename" => './tank.png',        "first" => "Ta",                "second" => "nk",       "source" => "http://fav.me/d4mpza7"),
    "winona"    => array("filename" => './winona.png',      "first" => "Wino",              "second" => "na",       "source" => "http://fav.me/d56dunz"),
    "break10"    => "The only OC allowed",
    "faust"     => array("filename" => './faust.png',       "first" => "Lauren",            "second" => " Faust",    "source" => "http://fav.me/d4f7f6n"),
    //""        => array("filename" => './.png', "first" => "", "second" => "", "source" => ""),
);
?>