<?php
$ponies = array(
    "break0"    => "Mane six",
    "twilight"  => array("filename" => './twilight.png',    "first" => "Twilight",          "second" => " Sparkle", "source" => "https://www.deviantart.com/xpesifeindx/art/Twilight-Sparkle-13-339906224"),
    "rarity"    => array("filename" => './rarity.png',      "first" => "Rari",              "second" => "ty",       "source" => "http://fav.me/d53i50w"),
    "applejack" => array("filename" => './applejack.png',   "first" => "Apple",             "second" => "jack",     "source" => "https://www.deviantart.com/daringdashie/art/You-don-t-want-to-mess-with-AJ-298188442"),
    "rainbow"   => array("filename" => './rainbow.png',     "first" => "Rainbow",           "second" => " Dash",    "source" => "http://fav.me/d5ztqnj"),
    "flutter"   => array("filename" => './fluttershy.png',  "first" => "Flutter",           "second" => "shy",      "source" => "https://www.deviantart.com/theponymuseum/art/I-Um-361935407"),
    "pinkie"    => array("filename" => './pinkie.png',      "first" => "Pinkie",            "second" => " Pie",     "source" => "https://www.deviantart.com/kysss90/art/Pinkie-Pie-by-KyssS-353498032"),
    "break1"    => "Dragons",
    "spike"     => array("filename" => './spike.png',       "first" => "Spi",               "second" => "ke",       "source" => "http://fav.me/d5mkrl5"),
    "break2"    => "The CMC",
    "sweetie"   => array("filename" => './sweetie.png',     "first" => "Sweetie",           "second" => " Belle",   "source" => "https://www.deviantart.com/purplefairy456/art/Sittin-Pretty-253543783"),
    "scoot"     => array("filename" => './scootaloo.png',   "first" => "Scoota",            "second" => "loo",      "source" => "https://www.deviantart.com/kamyk962/art/Scootaloo-Vector-350734818"),
    "abloom"    => array("filename" => './applebloom.png',  "first" => "Apple",             "second" => " Bloom",   "source" => "https://www.deviantart.com/lilcinnamon/art/Apple-Bloom-Smiling-adorably-279049627"),
    "babs"      => array("filename" => './babs.png',        "first" => "Babs",              "second" => " Seed",    "source" => "https://www.deviantart.com/robzombiefan2121/art/Babs-Seed-CMC-Ceremony-347519903"),
    "break3"    => "Princesses",
    "celestia"  => array("filename" => './celestia.png',    "first" => "Princess Cele",     "second" => "stia",     "source" => "https://www.deviantart.com/spier17/art/Princess-Celestia-365311804"),
    "luna"      => array("filename" => './luna.png',        "first" => "Princess Lu",       "second" => "na",       "source" => "http://fav.me/d5f8k46"),
    "cadence"   => array("filename" => './cadence.png',     "first" => "Princess Ca",       "second" => "dance",    "source" => "https://www.deviantart.com/proenix/art/Luna-327924438"),
    "twilight_p"=> array("filename" => './twilight_p.png',  "first" => "Princess Twi",      "second" => "light",    "source" => "https://www.deviantart.com/kamyk962/art/Twilight-Sparkle-Alicorn-Vector-355000137"),
    "break4"    => "Stallions",
    "bigmac"    => array("filename" => './bigmac.png',      "first" => "Big Mac",           "second" => "intosh",   "source" => "https://www.deviantart.com/baumkuchenpony/art/angry-Big-Macintosh-295025628"),
    "shining"   => array("filename" => './shining.png',     "first" => "Shining",           "second" => " Armor",   "source" => "https://www.deviantart.com/sakatagintoki117/art/Shining-Armor-339746794"),
    "blueblood" => array("filename" => './blueblood.png',   "first" => "Blue",              "second" => "blood",    "source" => "https://www.deviantart.com/peachspices/art/Prince-Blueblood-Gala-227552672"),
    "braeburn"  => array("filename" => './braeburn.png',    "first" => "Brae",              "second" => "burn",     "source" => "https://www.deviantart.com/sofunnyguy/art/To-me-You-didn-t-need-to-349344419"),
    "fancy"     => array("filename" => './fancy.png',       "first" => "Fancy",             "second" => " Pants",   "source" => "https://www.deviantart.com/the-smiling-pony/art/Fancy-Pants-294146468"),
    "break5"    => "Zebras",
    "zecora"    => array("filename" => './zecora.png',      "first" => "Zeco",              "second" => "ra",       "source" => "http://fav.me/d5bfzw0"),
    "break6"    => "Antagonists",
    "nmm"       => array("filename" => './nmm.png',         "first" => "Nightmare",         "second" => " Moon",    "source" => "http://fav.me/d566bx9"),
    "chrys"     => array("filename" => './chrysalis.png',   "first" => "Queen Chry",        "second" => "salis",    "source" => "https://www.deviantart.com/delectablecoffee/art/Chrysalis-01-324358079"),
    "sombra"    => array("filename" => './sombra.png',      "first" => "King Somb",         "second" => "ra",       "source" => "https://www.deviantart.com/90sigma/art/King-Sombra-335049960"),
    "lightning" => array("filename" => './lightning.png',   "first" => "Lightning",         "second" => " Dust",    "source" => "https://www.deviantart.com/puetsua/art/Lightning-Dust-is-ready-SVG-368971308"),
    "break66"   => "Reformed antagonists",
    "sunset"    => array("filename" => './sunset.png',      "first" => "Sunset",            "second" => " Shimmer", "source" => "https://www.deviantart.com/givralix/art/Pony-Sunset-Shimmer-429912436"),
    "trixie"    => array("filename" => './trixie.png',      "first" => "Tri",               "second" => "xie",      "source" => "https://www.deviantart.com/durpy/art/The-Great-and-Naked-Trixie-261877859"),
    "gilda"     => array("filename" => './gilda.png',       "first" => "Gil",               "second" => "da",       "source" => "https://www.deviantart.com/peachspices/art/Meanie-Gilda-253525605"),
    "discord"   => array("filename" => './discord.png',     "first" => "Dis",               "second" => "cord",     "source" => "http://fav.me/d5ke8hx"),
    "starlight" => array("filename" => './starlight.png',   "first" => "Starlight",         "second" => " Glimmer", "source" => "https://www.deviantart.com/djdavid98/art/Proud-Starlight-Glimmer-S05E01-518542055"),
    "starlight2"=> array("filename" => './starlight2.png',  "first" => "Starlight",         "second" => " Glimmer", "source" => ["https://www.deviantart.com/djdavid98/art/Proud-Starlight-Glimmer-S05E01-518542055", "https://www.deviantart.com/8-notes/art/Cute-Starlight-Glimmer-575292934"],
        "hidden" => true),
    "break7"    => "Minor characters",
    "diamond"   => array("filename" => './diamond.png',     "first" => "Diamond",           "second" => " Tiara",   "source" => "https://www.deviantart.com/liggliluff/art/Diamond-Tiara-Snooty-280511569"),
    "silver"    => array("filename" => './silver.png',      "first" => "Silver",            "second" => " Spoon",   "source" => "https://www.deviantart.com/piranhaplant1/art/Silver-Spoon-Vector-309983569"),
    "cheerilee" => array("filename" => './cheerilee.png',   "first" => "Cheeri",            "second" => "lee",      "source" => "https://www.deviantart.com/vector-brony/art/Cheerilee-355586783"),
    "granny"    => array("filename" => './granny.png',      "first" => "Granny",            "second" => " Smith",   "source" => "https://www.deviantart.com/kna/art/Granny-Smith-revectorized-269355154"),
    "spitfire"  => array("filename" => './spitfire.png',    "first" => "Spit",              "second" => "fire",     "source" => "https://www.deviantart.com/themedic22/art/Spitfire-312753935"),
    "fleur"     => array("filename" => './fleur.png',       "first" => "Fleur",             "second" => " De Lis", "source" => "https://www.deviantart.com/ahkreem/art/The-Mare-of-Many-Names-272334805"),
    "break8"    => "Background ponies",
    "bonbon"    => array("filename" => './bonbon.png',      "first" => "Bon",               "second" => "bon",      "source" => "http://fav.me/d5ioklg"),
    "lyra"      => array("filename" => './lyra.png',        "first" => "Ly",                "second" => "ra",       "source" => "https://www.deviantart.com/stinkehund/art/Lyra-sitting-211573400"),
    "derpy"     => array("filename" => './derpy.png',       "first" => "Der",               "second" => "py",       "source" => "https://www.deviantart.com/starshinecelestalis/art/Derpy-Hooves-Flying-Vector-387780671"),
    "doctor"    => array("filename" => './doctor.png',      "first" => "Doctor",            "second" => " Whooves", "source" => "https://www.deviantart.com/chainchomp2/art/Smiling-Doctor-Whooves-377244138"),
    "golden"    => array("filename" => './golden.png',      "first" => "Golden",            "second" => " Harvest", "source" => "https://www.deviantart.com/sirleandrea/art/Carrot-Top-210570361"),
    "octavia"   => array("filename" => './octavia.png',     "first" => "Octa",              "second" => "via",      "source" => "https://www.deviantart.com/kooner-cz/art/Octavia-Classy-258205887"),
    "vinyl"     => array("filename" => './vinyl.png',       "first" => "Vinyl",             "second" => " Scratch", "source" => "https://www.deviantart.com/moongazeponies/art/Vinyl-Scratch-No-Shades-298768226"),
    "vinyl2"    => array("filename" => './vinyl2.png',      "first" => "Vinyl",             "second" => " Scratch", "source" => "https://www.deviantart.com/moongazeponies/art/Vinyl-Scratch-210726958",
        "hidden" => true),
    "break9"    => "Pets",
    "angel"     => array("filename" => './angel.png',       "first" => "An",                "second" => "gel",      "source" => "https://www.deviantart.com/404compliant/art/Angel-vector-279536188"),
    "opal"      => array("filename" => './opal.png',        "first" => "Opal",              "second" => "escence",  "source" => "https://www.deviantart.com/atomicgreymon/art/Opal-aka-Opalescence-MLP-FiM-209622222"),
    "gummy"     => array("filename" => './gummy.png',       "first" => "Gum",               "second" => "my",       "source" => "http://fav.me/d5j6tze"),
    "owl"       => array("filename" => './owl.png',         "first" => "Owlow",             "second" => "iscious",  "source" => "http://fav.me/d5kibis"),
    "tank"      => array("filename" => './tank.png',        "first" => "Ta",                "second" => "nk",       "source" => "https://www.deviantart.com/brainchildeats/art/Tank-280028383"),
    "winona"    => array("filename" => './winona.png',      "first" => "Wino",              "second" => "na",       "source" => "https://www.deviantart.com/abydos91/art/Winonna-Apple-Family-Portrait-313054847"),
    "break10"    => "The only OC allowed",
    "faust"     => array("filename" => './faust.png',       "first" => "Lauren",            "second" => " Faust",    "source" => "http://fav.me/d4f7f6n"),
    //""        => array("filename" => './.png', "first" => "", "second" => "", "source" => ""),
);
?>